yarn.lock
- cleaning up yarn.lock
Using
- node v20.14.0
- npm v10.7.0
- yarn v1.22.22
- python 3.8.19 (after downgrade from 3.12.3)
Before the cleanup of yarn.lock file:
After the cleanup of yarn.lock file:
=> wrong version of `fsevents` into yarn.lock file caused issues when installing packages using node > v16.x

.github/workflows/node.js.yml
we were triggering a build on any push to this repo, modifying to match what we have in other repos to only trigger builds on PRs and pushes to master
=> only build on pushes to master and pull requests

integration-tests/README.md, integration-tests/basic-test-app/android/app/src/main/AndroidManifest.xml, integration-tests/basic-test-app/android/app/src/main/res/xml/network_security_config.xml, integration-tests/basic-test-app/android/build.gradle, integration-tests/basic-test-app/app/(tabs)/index.tsx, integration-tests/basic-test-app/app/_layout.tsx, integration-tests/basic-test-app/helpers/generateSpans.ts, integration-tests/helpers/embrace_server.ts, integration-tests/helpers/invoke_embrace_server.ts, integration-tests/helpers/session.ts, integration-tests/helpers/span.ts, integration-tests/specs/session.test.ts, integration-tests/specs/tracer_provider.test.ts, integration-tests/typings/embrace.d.ts, integration-tests/wdio.conf.ts
A few changes to the integration tests after testing with the actual Android SDK:
* newest version is sending payloads to v2/spans and not the only session endpoint so update types there
* update test expectations around the spans to reflect how they actual behave in the SDK
=> EMBR-4289 test updates after integration with android

packages/core/android/src/main/java/io/embrace/embracewrapper/EmbraceManagerModule.java
See https://embrace-io.slack.com/archives/CG568LLGP/p1722260551836959
The Android SDK currently sets the start/end timestamps to 0 when receiving that as a parameter. Going forward when receiving 0 it will instead set the current time but since we're still pointing to a version without that change going to instead pass `null` to be safe
=> EMBR-4612 use nulls for timestamps on android instead of 0

packages/core/src/__tests__/embrace.test.ts, packages/core/src/__tests__/network.test.ts, packages/core/src/index.ts, packages/core/src/utils/ErrorUtil.ts
Seeing a test failure on GHA that I wasn't seeing locally, I couldn't figure out the exact root cause but I thought it might be related to some of tests mocking the `NativeModules` inline, I think jest hoists those calls to the top of the file so there might be some weirdness when they're run in parallel
I'll see if this passes, moved all mocking to happen once at the top of each test file
=> EMBR-4627 fix flaky tests

packages/core/ios/RNEmbrace/EmbraceManager.swift
No API exposed by the iOS SDK currently for removing properties from all lifespans, however it is safe to call `removeProperty` multiple times ourselves to make sure we've gotten rid of the property we've added
=> EMBR-4625 handle removing session properties for all lifespans

.github/workflows/codeql.yml
By default CodeQL was trying to run Ruby, probably due to tooling used for pod files. Adding configuration and just turning on javascript-typescript for now, will address turning on the other languages (java-kotlin + swift) later as tech debt
=> Add advanced codeql

packages/core/scripts/setup/android.ts, packages/core/scripts/setup/ios.ts
I introduced this in https://github.com/embrace-io/embrace-react-native-sdk/pull/197 and the error handling was assuming that if `fs.openSync` threw an error it was because the file already exists, but there are other cases possible (like parent directory missing) so adding an extra check here
=> EMBR-5336 fix fs error handling in install scripts

DEVELOPING.md, integration-tests/README.md, integration-tests/wdio.conf.ts
Probably best to read `integration-tests/README.md` as a rendered page
Will tackle Browserstack hook up next so likely the way we run integration tests will get updated again
=> EMBR-5134 update READMEs to include test harness and app templates

.github/dependabot.yml
This week we had PRs for:
* @babel/preset-env
* @babel/preset-react
* @babel/core
* @babel/preset-typescript 
Probably makes sense to treat these all as a group
=> make a dependabot group for babel

packages/apollo-graphql/README.md
apollo-graphql package name is wrong in README.
N/A
N/A
=> doc: wrong package name in apollo-graphql README

integration-tests/README.md
Wasn't able to see this until the action was merged:
=> running integration tests manually

package.json
I *think* this will do the right thing based on reading: https://github.com/lerna/lerna/tree/main/libs/commands/publish, the idea is to first run `lerna version` so that all the package.json files have the correct next version *then* build each package which should mean that the core package specifically has the right version built into `lib/package.json`. After that we do `lerna publish from-git` which unlike the base command doesn't try and run `version` again.
I didn't try and fully test this I think the easiest way to verify might be to just to run through this workflow next time we release and see if it works as expected. It might be that `from-package` is the option we want, it also skips the version step but does a different check
=> EMBR-5586 do version bump before build

integration-tests/browserstack.conf.ts, integration-tests/build-test-app.sh, integration-tests/templates/rn71-template/package.json, integration-tests/templates/rn72-template/package.json, integration-tests/templates/rn73-template/package.json, integration-tests/templates/rn74-template/package.json, integration-tests/templates/rn75-template/package.json
Previously for integration tests app were being created under `embrace-react-native-sdk/integration-tests`, however this caused conflicts with the test apps' dependencies since they were looking into the `node_modules/` folders above them. Change here is to create the apps in an isolated temporary directory
=> EMBR-5733 create apps for integration testing in a separate directory

.github/workflows/integration-test.yml, DEVELOPING.md
Misinterpreted the `branches` filter, that is being applied to the target branch whereas we want to run integration tests whenever a branch named 'release/' is opened, using the example from: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-your-pull_request-workflow-based-on-the-head-or-base-branch-of-a-pull-request
=> run integration tests based on head branch name rather than base

integration-tests/test-harness/src/screens/SpanTestingScreen.tsx, packages/core/src/index.ts
Was using this method wrong, the result of startView if it's successful is an id that should then be passed to `endView`
=> fix span testing screen

README.md, lerna.json, packages/action-tracker/package.json, packages/apollo-graphql/package.json, packages/core/package.json, packages/react-native-navigation/package.json, packages/react-native-otlp/README.md, packages/react-native-otlp/package.json, packages/react-native-tracer-provider/package.json, packages/react-navigation/package.json, packages/screen-orientation/package.json, packages/spans/package.json, packages/webview-tracker/package.json
Embrace RN v5.2.0 to be released after Releases Freeze period (Jan, 2nd). Diff against last release (5.1.0): https://github.com/embrace-io/embrace-react-native-sdk/compare/v5.1.0...release/5.2.0
- `@embrace-io/react-native-otlp` going out, making the package public and releasable
- `@embrace-io/react-native` supporting `Network Span Forwarding` feature
- iOS upgrade to `v6.6.0`
- fixed Android Unit Tests that were passing without running
=> Release v5.2.0

packages/core/src/__tests__/error.test.ts, packages/core/src/__tests__/index.test.ts, packages/core/src/api/component.ts, packages/core/src/hooks/useEmbrace.test.ts, packages/core/src/index.ts, packages/core/src/utils/error.ts
- refactored tests that cover the `initialize` main method for RN sdk
- console log/warn messages displayed across the workflow silenced at least for this file for now and adding checks around those (those were making the workflow noisy and difficult to inspect in case real failures) .
=> (fix) refactored JS unit tests for `index.ts` file

packages/core/src/__tests__/error.test.ts, packages/core/src/__tests__/index.test.ts, packages/core/src/api/component.ts, packages/core/src/utils/error.ts
Component render errors + unhandled promise rejections were missing the last parameter when calling `logMessageWithSeverityAndProperties`
=> EMBR-6294 fix calls to logMessageWithSeverityAndProperties

packages/core/scripts/__tests__/__mocks__/ios/testMock.xcodeproj/project.pbxproj, packages/core/scripts/setup/ios.ts, packages/core/scripts/setup/uninstall.ts, packages/core/scripts/util/ios.ts
Previously we triggered source map generation on iOS by updating the react native build phase with:
```
export SOURCEMAP_FILE="$CONFIGURATION_BUILD_DIR/main.jsbundle.map"
```
when this variable is set the react native xcode script emits a map file:
https://github.com/facebook/react-native/blob/17c34295a18c707ea28dc7f6f8566bdb57472b83/packages/react-native/scripts/react-native-xcode.sh#L127
however the problem was with our naming, "$CONFIGURATION_BUILD_DIR/main.jsbundle.map" is exactly the same name that gets used for `PACKAGER_SOURCEMAP_FILE`: https://github.com/facebook/react-native/blob/17c34295a18c707ea28dc7f6f8566bdb57472b83/packages/react-native/scripts/react-native-xcode.sh#L133 and the last thing the script does is `rm $PACKAGER_SOURCEMAP_FILE` which deletes the source map file we …
=> EMBR-5980 fix sourcemap upload

integration-tests/basic-test-app/android/app/src/main/embrace-config.json, integration-tests/set-embrace-config.js, packages/core/android/dependencies.gradle, packages/core/android/gradle.properties, packages/core/android/src/main/java/io/embrace/rnembracecore/EmbraceManagerModule.java, packages/core/package.json, packages/core/scripts/__tests__/__mocks__/android/MainApplication.java, packages/core/scripts/__tests__/__mocks__/android/MainApplication.kt, packages/core/scripts/setup/patches/patch.ts, packages/core/scripts/util/android.ts, packages/core/test-project/android/app/src/test/java/io/embrace/rnembracecoretest/RNEmbraceCoreTest.kt, packages/react-native-navigation/README.md, packages/react-native-navigation/package.json, packages/react-native-otlp/README.md, packages/react-native-otlp/android/dependencies.gradle, packages/react-native-otlp/android/src/main/java/io/embrace/rnembraceotlp/RNEmbraceOTLPModule.kt, packages/react-native-otlp/package.json, packages/react-native-otlp/test-project/android/app/src/test/java/io/embrace/rnembraceotlptest/RNEmbraceOTLPTest.kt, packages/react-native-redux/package.json, packages/react-native-tracer-provider/android/dependencies.gradle, packages/react-native-tracer-provider/package.json, packages/react-native-tracer-provider/test-project/android/app/src/test/java/io/embrace/reactnativetracerprovidertest/ReactNativeTracerProviderTest.kt, yarn.config.cjs
Main changes are:
- moving specifying the app framework from the `start` call in code to an attribute in the JSON config
- adding a dependency on io.embrace:embrace-internal-api and grabbing the RN interface from there
=> EMBR-6049 upgrade to Android 7.0.0

packages/react-native-navigation/src/instrumentation/utils/spanFactory.ts
If a crash happens right after this span is created it's possible that its attributes will not have been persisted to disk by the native SDK, instead since we know the attributes ahead of time include them when starting the span
=> EMBR-6828 add navigation attributes when span starts

packages/core/package.json, packages/core/test-project/ios/Podfile.lock, packages/react-native-navigation/package.json, packages/react-native-otlp/package.json, packages/react-native-otlp/test-project/ios/Podfile.lock, packages/react-native-redux/package.json, packages/react-native-tracer-provider/package.json, packages/react-native-tracer-provider/test-project/ios/Podfile.lock, yarn.config.cjs
Take advantage of fixes we are missing from the latest iOS SDK, specifically for network capture (see https://github.com/embrace-io/embrace-react-native-sdk/issues/473)
=> update iOS SDK dependency
