README.md
lerna.json
packages/action-tracker/package.json
packages/apollo-graphql/package.json
packages/core/package.json
packages/react-native-navigation/package.json
packages/react-navigation/package.json
packages/screen-orientation/package.json
packages/webview-tracker/package.json

Update Packages to 4.0.1
Update Readme

Update RN 4.0 + Readme Change

---

packages/core/android/src/main/java/io/embrace/embracewrapper/EmbraceManagerModule.java
packages/core/ios/RNEmbrace/EmbraceManager.m
packages/spans/src/index.ts

Add startTime and endTime to spans

Changes in spans

---

.github/workflows/node.js.yml

**WHAT**:<br>
**WHY**:<br>
**WHO**:<br>

Github Actions - Upgrade Node version (18.x)

---

packages/core/scripts/__tests__/__mocks__/buildWithoutSwazzler.gradle
packages/core/scripts/__tests__/scripts.test.ts

The test was adding and removing a line to the mock file but in removing it it was leaving behind trailing whitespace which ended up as part of git changes

Fix extra lines added to test mock

---

.github/workflows/node.js.yml

wrong indentation when I committed here: https://github.com/embrace-io/embrace-react-native-sdk/commit/115961e80734c445ebd853c952d1f4f1a2a300cb

fix typo preventing actions on PRs

---

examples/react-native-test-suite/App.js
integration-tests/basic-test-app/app/_layout.tsx
packages/core/RNEmbrace.podspec
packages/core/android/src/main/java/io/embrace/embracewrapper/EmbraceManagerModule.java
packages/core/ios/RNEmbrace.xcodeproj/project.pbxproj
packages/core/ios/RNEmbrace/EmbraceManager.h
packages/core/ios/RNEmbrace/EmbraceManager.m
packages/core/ios/RNEmbrace/EmbraceManager.swift
packages/core/ios/RNEmbrace/EmbraceOTelSpanHelper.h
packages/core/ios/RNEmbrace/EmbraceOTelSpanHelper.m
packages/core/ios/RNEmbrace/RNEmbrace-Bridging-Header.h
packages/core/src/__tests__/embrace.test.ts
packages/core/src/index.ts

Create Swift class to use the new methods from iOS 6.0

iOS 6.0 Migration

---

packages/core/RNEmbrace.podspec
packages/core/ios/RNEmbrace/EmbraceManager.swift
packages/core/test-project/ios/Podfile
packages/core/test-project/ios/Podfile.lock
packages/core/test-project/ios/RNEmbraceTestProject.xcodeproj/project.pbxproj
packages/core/test-project/ios/RNEmbraceTests/RNEmbraceTests.swift

* re-enable failing unit tests
* remove unneeded import
* fix keys added to resource payload

EMBR-4634 update to ios 6.3.0

---

packages/screen-orientation/__tests__/screen-orientation-tracker.test.ts
packages/screen-orientation/src/index.ts

we had otherwise renamed this method from logBreadcrumb -> addBreadcrumb

EMBR-4795 use addBreadcrumb

---

packages/core/android/src/main/java/io/embrace/embracewrapper/EmbraceManagerModule.java

Fixing change here that was made to the wrong line: https://github.com/embrace-io/embrace-react-native-sdk/pull/69/files#diff-a015f11c849963bba1e0ffad3c00d204b91daaebe9b63516e63214a32c799d3d

EMBR-4804 fix android start view

---

packages/core/RNEmbrace.podspec
packages/core/ios/RNEmbrace/EmbraceManager.swift
packages/core/test-project/ios/Podfile
packages/core/test-project/ios/Podfile.lock
packages/core/test-project/ios/RNEmbraceTestProject.xcodeproj/project.pbxproj
packages/core/test-project/ios/RNEmbraceTests/RNEmbraceTests.swift

not sure if the changes to `packages/core/test-project/ios/RNEmbraceTestProject.xcodeproj/project.pbxproj` are required but I do see the unit tests passing on this branch locally

EMBR-4935 unit tests passing on 6.4.0

---

integration-tests/basic-test-app/ios/basictestapp.xcodeproj/project.pbxproj
jest.config.js
packages/core/src/index.ts

- removing Embrace-Info.plist reference (basic-test-app)
- tweak for ts type (Properties)
- jest config

(fix): Removing Embrace-Info.plist reference (basic-test-app) + tweak for ts type (Properties) + jest config

---

integration-tests/basic-test-app/ios/Podfile.lock
integration-tests/basic-test-app/ios/basictestapp.xcodeproj/project.pbxproj
packages/core/RNEmbrace.podspec
packages/core/test-project/ios/Podfile
packages/core/test-project/ios/Podfile.lock
packages/core/test-project/ios/RNEmbraceTestProject.xcodeproj/project.pbxproj

switching from the rc since the version is now released

updating to ios 6.4.0

---

.github/CODEOWNERS
.github/dependabot.yml
.github/workflows/dependency-review.yml
DEVELOPING.md
README.md
packages/core/android/gradle.properties
packages/core/package.json

Updating 5.0 with the latest changes from main
For `packages/core/package.json` rather than listing all the new iOS files I went back to using "ios/RNEmbrace", we end up including an extra Info.plist file but it's empty so I think not a big deal

Jpmunz/update 5.0 latest main

---

.github/workflows/ios.unit-test.yml
integration-tests/update-local-embrace.sh
package.json
packages/core/package.json
packages/core/test-project/RNEmbraceTests.xctestplan
packages/core/test-project/ios/Podfile
packages/core/test-project/ios/RNEmbraceTestProject.xcodeproj/xcshareddata/xcschemes/RNEmbraceTests.xcscheme
packages/core/test-project/ios/RNEmbraceTestProject.xcworkspace/contents.xcworkspacedata
packages/core/test-project/ios/RNEmbraceTests/RNEmbraceTests.swift
run-ios-tests.sh

In https://github.com/embrace-io/embrace-react-native-sdk/pull/140 I tried to get the iOS tests running across multiple projects but ran into issues
Separating the changes into this branch to try and isolate what is failing

EMBR-5056 ios tests across multiple projects

---

packages/react-native-tracer-provider/ios/ReactNativeTracerProvider/ReactNativeTracerProviderModule.swift
packages/react-native-tracer-provider/native-src/ios/Podfile.lock
packages/react-native-tracer-provider/native-src/ios/ReactNativeTracerProviderTests/ReactNativeTracerProviderTests.swift
packages/react-native-tracer-provider/src/__tests__/tracerProvider.test.ts
packages/react-native-tracer-provider/src/util.ts

* fix tests due to opentelemetry upgrade
* consistent representations for boolean attributes

EMBR-5129 consistent boolean strings

---

.github/workflows/ios.unit-test.yml
package.json
packages/react-native-tracer-provider/native-src/ios/ReactNativeTracerProvider.xcodeproj/project.pbxproj
packages/react-native-tracer-provider/native-src/ios/ReactNativeTracerProvider.xcodeproj/xcshareddata/xcschemes/ReactNativeTracerProvider.xcscheme
packages/react-native-tracer-provider/native-src/ios/ReactNativeTracerProvider.xctestplan
packages/react-native-tracer-provider/native-src/ios/ReactNativeTracerProviderTests/ReactNativeTracerProviderTests.swift

Copy over same changes from core, see if the tests pass consistently

EMBR-5135 fix ios tests in tracer provider package

---

.github/workflows/ios.unit-test.yml
integration-tests/basic-test-app/ios/Podfile.lock
integration-tests/basic-test-app/ios/basictestapp.xcodeproj/project.pbxproj
packages/core/RNEmbrace.podspec
packages/core/test-project/ios/Podfile
packages/core/test-project/ios/Podfile.lock
packages/core/test-project/ios/RNEmbraceTestProject.xcodeproj/project.pbxproj

Tested with a basic session to Embrace: https://dash.embrace.io/app/cvKeD/grouped_sessions/last_1_hour/079EB8D9D9BC48ECB69AF5827B1EB7A1/39ABA942734B4C44B0E52E6203F0A414@/07FAB87AB54E4C5BB779798C787ADE19?first=39ABA942734B4C44B0E52E6203F0A414&last=07FAB87AB54E4C5BB779798C787ADE19&source=session
After merge cut a release branch and do a bit more QA before releasing the updated 5.0.1 RN packages

EMBR-5153 upgrade to ios 6.4.2

---

packages/core/scripts/__tests__/uninstall.android.test.ts
packages/core/scripts/setup/android.ts
packages/core/scripts/setup/ios.ts

Addressing the following code scanning alerts:
* https://github.com/embrace-io/embrace-react-native-sdk/security/code-scanning/4
* https://github.com/embrace-io/embrace-react-native-sdk/security/code-scanning/1
* https://github.com/embrace-io/embrace-react-native-sdk/security/code-scanning/2

EMBR-3962 address race condition alerts

---

integration-tests/test-harness/src/EmbraceReactNativeTestHarness.tsx

Fixing reference passed down to NavigationTracker component (@opentelemetry/instrumentation-react-native-navigation)

[EMB-5402] Fix navigation instrumentation for bare react native test harness

---

.gitignore
CODE_OF_CONDUCT.md
CONTRIBUTING.md
DEVELOPING.md
README.md
packages/core/README.md

- Adding CODE_OF_CONDUCT.md file.
- Updating CONTRIBUTING.md file.
- Tweaks for packages/core/README.md
- adding ios folders to .gitignore

[EMBR-4155] Update contributing markdown

---

DEVELOPING.md

Wanted to add a couple steps we've been doing to resolve local development issues

document some local troubleshooting steps

---

integration-tests/templates/rn71-template/android/build.gradle
integration-tests/templates/rn72-template/android/build.gradle
integration-tests/templates/rn73-template/android/build.gradle
integration-tests/templates/rn74-template/android/build.gradle
integration-tests/templates/rn75-template/android/build.gradle
packages/react-native-otlp/android/dependencies.gradle
packages/react-native-otlp/android/src/main/java/io/embrace/rnembraceotlp/RNEmbraceOTLPModule.kt

- custom export for traces and logs

[EMBR-5552] Integrate custom export config for Traces and Logs

---

NATIVE_MODULE_DEVELOPING.md
packages/core/android/build.gradle
packages/core/android/gradle/wrapper/gradle-wrapper.properties
packages/react-native-otlp/android/build.gradle
packages/react-native-otlp/android/gradle/wrapper/gradle-wrapper.properties
packages/react-native-tracer-provider/android/build.gradle
packages/react-native-tracer-provider/android/gradle/wrapper/gradle-wrapper.properties

@facostaembrace it appears that a few of the issues from the ticket were already fixed in the core package's gradle files, I think these were the only ones remaining let me know if you see something I've missed

EMBR-5820 update core package gradle values

---

packages/core/android/src/main/java/io/embrace/rnembracecore/EmbraceManagerModule.java
packages/core/test-project/android/app/build.gradle.kts
packages/core/test-project/android/app/src/test/java/io/embrace/rnembracecoretest/RNEmbraceCoreTest.kt
packages/react-native-tracer-provider/test-project/android/app/build.gradle.kts
packages/react-native-tracer-provider/test-project/android/app/src/test/java/io/embrace/reactnativetracerprovidertest/ReactNativeTracerProviderTest.kt

- Introducing support for w3ctraceparent header
- Unit tests

[EMBR-5717] Android - Support for w3c traceparent header

---

packages/core/android/src/main/java/io/embrace/rnembracecore/EmbraceManagerModule.java

**WHAT**:<br>
**WHY**:<br>
**WHO**:<br>

(fix): Update Java syntax for older RN version

---

interfaces/index.ts
packages/core/src/__tests__/embrace.test.ts
packages/core/src/index.ts

**WHAT**:<br>
**WHY**:<br>
**WHO**:<br>

(fix): removing enum

---

integration-tests/test-harness/src/EmbraceReactNativeTestHarness.tsx

- fixing navigation for bare react native apps (test-harness)

[EMBR-5981] Fix navigation instrumentation for a bare RN app

---

integration-tests/test-harness/src/screens/OTLPTestingScreen.tsx

**WHAT**:<br>
**WHY**:<br>
**WHO**:<br>

(fix) moving return statement after the use of useCallback hook

---

common/js/interfaces.ts
integration-tests/embrace-configs/real-unhandled-tracking.json
integration-tests/set-embrace-config.js
integration-tests/test-harness/src/screens/LogTestingScreen.tsx
packages/core/package.json
packages/core/src/__tests__/error.test.ts
packages/core/src/__tests__/index.test.ts
packages/core/src/index.ts
packages/core/src/utils/error.ts
yarn.lock

docs: https://github.com/embrace-io/embrace-docs/pull/169

EMBR-6322 make unhandled promise rejection opt-in

---

packages/core/src/__tests__/index.test.ts
packages/core/src/utils/otlp.ts

- improving error log for otlp if throws

(fix) OTLP package to display real Metro exception

---

packages/react-native-otlp/README.md

Copying over updates from https://github.com/embrace-io/embrace-docs/pull/187

EMBR-6294 add instructions for ignoring urls

---

README.md

More permanent Slack community URL
**WHAT**:<br>
**WHY**:<br>
**WHO**:<br>

better Slack community URL in README

---

.github/workflows/android.unit-test.yml
.github/workflows/ci-gha-workflows.yaml
.github/workflows/codeql.yml
.github/workflows/dependency-review.yml
.github/workflows/integration-test.yml
.github/workflows/ios.unit-test.yml
.github/workflows/node.js.yml

See https://github.com/zizmorcore/zizmor

Run zizmor for static analysis of .github/workflows/

---

packages/core/android/gradle.properties
packages/core/package.json
packages/react-native-navigation/package.json
packages/react-native-otlp/package.json
packages/react-native-redux/package.json
packages/react-native-tracer-provider/package.json
yarn.config.cjs

Upgrading Android dependency => 7.6.0

upgrade native sdk dependencies
